name: Ansible Deploy

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: Validate Ansible Playbook Syntax
      run: |
        cd ansible
        ansible-playbook nginx-setup.yml --syntax-check
